### PR TITLE
Update error_logger handler for new cowboy_handler exits

### PR DESCRIPTION
**Pull request by fishcakez**
Required for https://github.com/ninenines/cowboy/pull/818. Nice to be able to remove so this code :).

### CODE REVIEW

**Comment by essen** [comment]
I don't think you can remove it considering middlewares and hooks execute without a try/catch, let alone other code like Gun which doesn't use Ranch.

**Comment by fishcakez** [comment]
Ok have reverted the removal of emulator filtering.

**Comment by essen** [comment]
Everything looks good, testing tomorrow. Thanks!

**Comment by essen** [comment]
Did you test it? Because it doesn't work here. The data structure seems to be a little different with exit.

**Comment by essen** [comment]
No need to edit, I got it, just curious.

**Comment by essen** [comment]
That one is pushed!

**Pull request merged**
